// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WalletTelegramBot.DataAccess;

#nullable disable

namespace WalletTelegramBot.Migrations;

[DbContext(typeof(WTBDBContext))]
[Migration("20240908190322_init")]
partial class init
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("public")
            .HasAnnotation("ProductVersion", "8.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("WalletTelegramBot.Domain.Incomes", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<decimal>("Amount")
                    .HasColumnType("numeric");

                b.Property<string>("Comment")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("Date")
                    .HasColumnType("timestamp without time zone");

                b.HasKey("Id");

                b.ToTable("Incomes", "public");
            });

        modelBuilder.Entity("WalletTelegramBot.Domain.Spendings", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<decimal>("Amount")
                    .HasColumnType("numeric");

                b.Property<string>("Comment")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<DateTime>("DateTime")
                    .HasColumnType("timestamp without time zone");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.HasKey("Id");

                b.ToTable("Spendings", "public");
            });
#pragma warning restore 612, 618
    }
}
